version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm run build && npm start"
    restart: unless-stopped
    networks:
      - fumigapp_network

networks:
  fumigapp_network:
    driver: bridge
