services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9001:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm run build && npm start"
    restart: unless-stopped
    networks:
      - fumigapp_network

  auth-service:
    build:
      context: ./microservices/auth-service
      dockerfile: Dockerfile
    ports:
      - "9002:3000"
    environment:
      - NODE_ENV=development
    restart: always
    networks:
      - fumigapp_network

  geolocation:
    build:
      context: ./microservices/geolocation
    ports:
      - "9003:3000"
    networks:
      - fumigapp_network

  weather-service:
    build:
      context: ./microservices/weather-service
      dockerfile: Dockerfile
    ports:
      - "9004:8080"
    env_file:
      - .env
    networks:
      - fumigapp_network

  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    ports:
      - "9005:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    restart: unless-stopped
    networks:
      - fumigapp_network

networks:
  fumigapp_network:
    driver: bridge
