// src/config/configKeys.ts

/**
 * Enum for configuration keys.
 */
export enum ConfigKeys {
  PORT = "PORT",
  WEATHER_URL = "WEATHER_URL",
  WEATHER_API_KEY = "WEATHER_API_KEY",
  OPENWEATHERMAP_KEY = "OPENWEATHERMAP_KEY",
  OPENWEATHERMAP_URL = "OPENWEATHERMAP_URL",
  OPENWEATHER_BASE_URL = "OPENWEATHER_BASE_URL",
}
